#!/usr/bin/env bash

set -e
[ "$DEP_DIR" ] && cd $DEP_DIR
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree ; exit 1
fi
if [ -z "$DEP_DIR" ]; then
    echo DEP_DIR var must point to ovpn3 dependency tree
    exit 1
fi
cd $DEP_DIR

rm -rf minicrypto
mkdir minicrypto

for target in osx osx-dbg ; do
    echo '***************' Minicrypto-32 $target
    TARGET=$target ARCH=i386 $O3/core/deps/minicrypto/build-minicrypto-osx
    echo '***************' Minicrypto-64 $target
    TARGET=$target ARCH=x86_64 $O3/core/deps/minicrypto/build-minicrypto-osx
    cd minicrypto/minicrypto-$target
    lipo -create */libminicrypto.a -output libminicrypto.a
    lipo -info libminicrypto.a
    cd ../..
done
exit 0
