#!/usr/bin/env bash
set -e
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree ; exit 1
fi
if [ -z "$DEP_DIR" ]; then
    echo DEP_DIR var must point to ovpn3 dependency tree
    exit 1
fi
cd $DEP_DIR

rm -rf boost
mkdir boost

export LINK_MODE=static
if [ "$OSX_ONLY" == "1" ]; then
    export TARGETS="osx osx-dbg"
else
    export TARGETS="ios ios-dbg iossim iossim-dbg osx osx-dbg"
fi

$O3/core/deps/boost/build-boost
exit 0
