#!/usr/bin/env bash
set -e
export DEP_DIR=${DEP_DIR:-$HOME/src/mac}
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree ; exit 1
fi
cd $DEP_DIR
rm -rf asio* boost* lz4* lzo* minicrypto openssl* polarssl* mbedtls* snappy*

echo "******* ASIO"
$O3/core/deps/asio/build-asio
if [ $MTLS = 0 ] ; then
    echo "******* MBEDTLS (skipped)"
else
    echo "******* MBEDTLS"

    # consider OSX_SERVER=0
    $O3/core/scripts/mac/build-mbedtls
fi
# 

$O3/core/deps/asio/build-asio
if [ $OSSL = 1 ] ; then
    echo "******* OPENSSL"
    $O3/core/scripts/mac/build-openssl
else
    echo "******* OPENSSL  (skipped)"
fi


echo "******* LZ4"
$O3/core/scripts/mac/build-lz4
echo "******* CITYHASH"
$O3/core/scripts/mac/build-cityhash

#echo "******* MINICRYPTO"
#$O3/core/scripts/mac/build-minicrypto
#echo "******* SNAPPY"
#$O3/core/scripts/mac/build-snappy
