#!/usr/bin/env bash

set -e
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree
    exit 1
fi
if [ -z "$DEP_DIR" ]; then
    echo DEP_DIR var must point to ovpn3 dependency tree
    exit 1
fi
cd $DEP_DIR

rm -rf jsoncpp
mkdir jsoncpp

if [ "$OSX_ONLY" != "1" ]; then
    for target in ios ios-dbg iossim iossim-dbg ; do
	echo '***************' TARGET $target
	TARGET=$target $O3/core/deps/jsoncpp/build-jsoncpp
    done
fi

for target in osx osx-dbg ; do
    echo '***************' TARGET $target
    TARGET=$target $O3/core/deps/jsoncpp/build-jsoncpp
done
exit 0
