#!/usr/bin/env bash
set -e
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree ; exit 1
fi
export DEP_DIR=${DEP_DIR:-$HOME/linux}
export TARGET=${TARGET:-linux}
cd $DEP_DIR
rm -rf asio* boost* lz4* lzo* minicrypto openssl* polarssl* snappy*
echo "******* ASIO"
$O3/core/deps/asio/build-asio
echo "******* MBEDTLS"
$O3/core/scripts/linux/build-mbedtls
echo "******* LZ4"
$O3/core/scripts/linux/build-lz4
echo "******* CITYHASH"
$O3/core/scripts/linux/build-cityhash

#$O3/core/scripts/linux/build-openssl x64
#$O3/core/scripts/linux/build-lzo
#$O3/core/scripts/linux/build-boost
#$O3/core/scripts/linux/build-snappy
#$O3/core/scripts/linux/consolidate-so
