#!/usr/bin/env bash
set -e
set -u
if [ -z "${O3:-}" ]; then
    echo O3 var must point to ovpn3 tree ; exit 1
fi
export DEP_DIR="${DEP_DIR:-$HOME/linux}"
export TARGET="${TARGET:-linux}"
cd "$DEP_DIR"
rm -rf asio* boost* lz4* lzo* minicrypto openssl* polarssl* snappy*
echo "******* ASIO"
"$O3"/core/deps/asio/build-asio
echo "******* xxHash"
"$O3"/core/deps/xxHash/build-xxHash
if [ "${MTLS:-1}" = 0 ] ; then
    echo "******* MBEDTLS (skipped)"
else
    echo "******* MBEDTLS"
    "$O3"/core/scripts/linux/build-mbedtls
fi
echo "******* LZ4"
"$O3"/core/scripts/linux/build-lz4

