#!/usr/bin/env bash
set -e
if [ -z "$1" ]; then
    echo "usage: build-openssl x64|arm"
    exit 1
fi
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree ; exit 1
fi
if [ -z "$DEP_DIR" ]; then
    echo DEP_DIR var must point to ovpn3 dependency tree
    exit 1
fi
cd $DEP_DIR

rm -rf openssl
mkdir openssl

export LINK_MODE=shared

case $1 in
x64*)
  export OPENSSL_TARGET=linux-x86_64
  ;;
arm*)
  export OPENSSL_TARGET=linux-armv4
  ;;
*)
  echo "unknown platform"
  exit 1
  ;;
esac

TARGET=linux $O3/core/deps/openssl/build-openssl
exit 0
