#!/usr/bin/env bash
rm -rf so
mkdir so
OPT=-d
[ -d boost ] && cp $OPT boost/stage-linux/lib/lib* so/
[ -d lzo ] && cp $OPT lzo/lzo-linux/lib/lib* so/
[ -d openssl ] && cp $OPT openssl/openssl-linux/lib/lib* so/
[ -d snappy ] && cp $OPT snappy/snappy-linux/lib/lib* so/
[ -d polarssl ] && cp $OPT polarssl/polarssl-linux/library/lib* so/
exit 0
