#!/bin/bash
set -e
pushd $O3/core
if [ "$(uname)" == "Darwin" ]; then
    . vars/vars-osx64
    . vars/setpath
    export GCC_EXTRA="$GCC_EXTRA -Wno-deprecated-declarations" # for daemon()
else
    . vars/vars-linux
    . vars/setpath
fi
popd
ASIO=1 MTLS=1 NOSSL=1 build ovpnagent
