repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v20.1.0'
    hooks:
      - id: clang-format
        files: \.[ch]pp$
        exclude: ^openvpn/common/unicode-impl\.hpp$
