#!/usr/bin/env bash
# Note: thread library may fail with PAGE_SIZE undefined.
# The pthread.h header makes reference to the PAGE_SIZE define however
# this only gets defined in <asm/page.h> which is not pulled in by any
# of the pthread.h includes.  A google-suggested fix was to add
# #include <sys/mman.h>, which does indeed work, but may not be the
# correct solution for all cases.
set -e
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree ; exit 1
fi
if [ -z "$DEP_DIR" ]; then
    echo DEP_DIR var must point to ovpn3 dependency tree
    exit 1
fi
cd $DEP_DIR
rm -rf boost
mkdir boost
export LINK_MODE=static
export TARGETS="android-a8a android-a8a-dbg android-a7a android-a7a-dbg"
export SDK_PATH_SCRIPT=$O3/core/vars/android-sdk-path
$O3/core/deps/boost/build-boost
exit 0
