#!/usr/bin/env bash

set -e
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree
    exit 1
fi

if [ -z "$DEP_DIR" ]; then
    echo DEP_DIR var must point to the dependency build directory
    exit 1
fi

. $O3/core/vars/android-sdk-path

cd $DEP_DIR
rm -rf mbedtls
mkdir -p mbedtls

# disable minicrypto for now
mini=0

TARGETS=${TARGETS:-android-a7a android-a8a android-x86}

for target in $TARGETS; do
    echo '***************' TARGET $target
    VERBOSE=1 TARGET=$target CMAKE_TARGET=android USE_MINICRYPTO=$mini MINICRYPTO_DIR=$(pwd)/minicrypto/minicrypto-$target $O3/core/deps/mbedtls/build-mbedtls
    [ "$ANDROID_DBG_ONLY" = "1" ] && exit
done
exit 0
