#!/usr/bin/env bash

set -e
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree ; exit 1
fi
if [ -z "$DEP_DIR" ]; then
    echo DEP_DIR var must point to ovpn3 dependency tree
    exit 1
fi
cd $DEP_DIR

. $O3/core/vars/android-sdk-path

rm -rf snappy
mkdir snappy

for target in android-a8a android-a8a-dbg android-a7a android-a7a-dbg ; do
    echo '***************' TARGET $target
    TARGET=$target $O3/core/deps/snappy/build-snappy
done
exit 0
