#!/bin/bash

#    OpenVPN -- An application to securely tunnel IP networks
#               over a single port, with support for SSL/TLS-based
#               session authentication and key exchange,
#               packet encryption, packet authentication, and
#               packet compression.
#
#    Copyright (C) 2018-2020 OpenVPN Inc.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License Version 3
#    as published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program in the COPYING file.
#    If not, see <http://www.gnu.org/licenses/>.

set -eu

# ensure this script works even when core is used as submodule, by setting
# O3/core/.git as git folder
export GIT_DIR=$(dirname $0)/../.git

MAJOR=3
BRANCH="$(git rev-parse --symbolic-full-name HEAD | cut -d/ -f3- | tr / _)"
COMMIT_ID="$(git rev-list HEAD -1 --abbrev-commit)"

echo "$MAJOR.git:$BRANCH:$COMMIT_ID"
