name: MSBuild

on: [push]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  buildDir: '${{ github.workspace }}/build'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: lukka/get-cmake@latest
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Restore from cache and install vcpkg
      uses: lukka/run-vcpkg@v6
      with:
        setupOnly: true
        vcpkgGitCommitId: '668f048edbadbd85db43084e6d93c6a45d262f5c'
        additionalCachedPaths: ${{ env.buildDir }}/vcpkg_installed

    - name: Run CMake with vcpkg.json manifest
      uses: lukka/run-cmake@main
      env:
        VCPKG_OVERLAY_PORTS: '${{ github.workspace }}/deps/vcpkg-ports'
      with:
        useVcpkgToolchainFile: true
        buildDirectory: '{{ env.buildDir }}'
        buildWithCMake: true
        cmakeAppendedArgs: '-DCLI_OVPNDCOWIN=ON'
