language: c

matrix:
  fast_finish: true
  include:

    - name: aarch64 real-hw tests
      arch: arm64
      script:
        - make test

    - name: PPC64LE real-hw tests
      arch: ppc64le
      script:
        - make test

    - name: IBM s390x real-hw tests
      arch: s390x
      script:
        - make test

    # tag-specific test
    - name: tag build
      if: tag =~ ^v[0-9]\.[0-9]
      os: linux
      script:
        - make -C tests checkTag
        - tests/checkTag "$TRAVIS_BRANCH"

    # oss-fuzz compilation test
    - name: Compile OSS-Fuzz targets
      script:
        - ./ossfuzz/travisoss.sh

    # Unicode lint
    # See https://github.com/lz4/lz4/issues/1018
    - name: Run Unicode lint
      script:
        - ./tests/unicode_lint.sh

  allow_failures:
    - env: ALLOW_FAILURES=true
