// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

package ch.protonmail.android.utils.nativelib;

import java.util.ArrayList;

import androidx.annotation.NonNull;

public final class Address {

    /*package*/ final String mAddressId;

    /*package*/ final String mAddressName;

    /*package*/ final ArrayList<OpenPgpKey> mKeys;

    public Address(@NonNull String addressId, @NonNull String addressName,
                   @NonNull ArrayList<OpenPgpKey> keys) {
        this.mAddressId = addressId;
        this.mAddressName = addressName;
        this.mKeys = keys;
    }

    @NonNull
    public String getAddressId() {
        return mAddressId;
    }

    /**
     * optional
     */
    @NonNull
    public String getAddressName() {
        return mAddressName;
    }

    @NonNull
    public ArrayList<OpenPgpKey> getKeys() {
        return mKeys;
    }

    @Override
    public String toString() {
        return "Address{" + "mAddressId=" + mAddressId + "," + "mAddressName=" + mAddressName + "," + "mKeys="
            + mKeys + "}";
    }

}
