// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

package ch.protonmail.android.utils.nativelib;

import androidx.annotation.NonNull;

public final class EncryptPackage {

    /*package*/ final byte[] mKeyPackage;

    /*package*/ final byte[] mDataPackage;

    public EncryptPackage(@NonNull byte[] keyPackage, @NonNull byte[] dataPackage) {
        this.mKeyPackage = keyPackage;
        this.mDataPackage = dataPackage;
    }

    @NonNull
    public byte[] getKeyPackage() {
        return mKeyPackage;
    }

    @NonNull
    public byte[] getDataPackage() {
        return mDataPackage;
    }

    @Override
    public String toString() {
        return "EncryptPackage{" + "mKeyPackage=" + mKeyPackage + "," + "mDataPackage=" + mDataPackage + "}";
    }

}
