// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

package ch.protonmail.android.utils.nativelib;

import java.util.concurrent.atomic.AtomicBoolean;

import androidx.annotation.NonNull;

public abstract class SrpClient {

    /**
     * ExpandHash
     */
    @NonNull
    public static native byte[] expandHash(@NonNull byte[] input);

    /**
     * SRP
     */
    @NonNull
    public static native SrpProofs generateProofs(int bitLength, @NonNull byte[] modulusRepr,
                                                  @NonNull byte[] serverEphemeralRepr,
                                                  @NonNull byte[] hashedPasswordRepr);

    @NonNull
    public static native byte[] generateVerifier(int bitLength, @NonNull byte[] modulusRepr,
                                                 @NonNull byte[] hashedPasswordRepr);

    private static final class CppProxy extends SrpClient {

        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef) {
            if (nativeRef == 0) {
                throw new RuntimeException("nativeRef is zero");
            }
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);

        public void destroy() {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) {
                nativeDestroy(this.nativeRef);
            }
        }

        protected void finalize() throws java.lang.Throwable {
            destroy();
            super.finalize();
        }
    }
}
